version: 2

shared:
  test: &shared_test
    working_directory: ~/zengin-py
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init
            git submodule foreach 'git pull origin master'
      - run:
          command: sudo pip install -U pip setuptools tox wheel twine
      - run:
          command: tox -e $TOX_ENV

jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/zengin-py
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init
            git submodule foreach 'git pull origin master'
      - run:
          command: sudo pip install -U pip setuptools tox wheel twine
      - run:
          command: ./bin/ci/deploy

  test_3_7:
    <<: *shared_test
    docker:
      - image: circleci/python:3.7
    environment:
      TOX_ENV: py37
  test_3_8:
    <<: *shared_test
    docker:
      - image: circleci/python:3.8
    environment:
      TOX_ENV: py38
  test_flake8:
    <<: *shared_test
    docker:
      - image: circleci/python:latest
    environment:
      TOX_ENV: flake8

workflows:
  version: 2
  build:
    jobs:
      - test_3_7
      - test_3_8
      - test_flake8
      - build:
          requires:
            - test_3_7
            - test_3_8
            - test_flake8
          filters:
            branches:
              only: master

