version: 2

shared:
  test: &shared_test
    working_directory: ~/zengin-py
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init
            git submodule foreach 'git pull origin master'
      - run:
          command: sudo pip install -U pip setuptools tox wheel twine
      - run:
          command: tox -e $TOX_ENV

jobs:
  build_2_7:
    <<: *shared_test
    docker:
      - image: circleci/python:2.7
    environment:
      TOX_ENV: py27
  build_3_4:
    <<: *shared_test
    docker:
      - image: circleci/python:3.4
    environment:
      TOX_ENV: py34
  build_3_5:
    <<: *shared_test
    docker:
      - image: circleci/python:3.5
    environment:
      TOX_ENV: py35
  build_3_6:
    <<: *shared_test
    docker:
      - image: circleci/python:3.6
    environment:
      TOX_ENV: py36
  build_3_7:
    <<: *shared_test
    docker:
      - image: circleci/python:3.7
    environment:
      TOX_ENV: py37
  build_flake8:
    <<: *shared_test
    docker:
      - image: circleci/python:latest
    environment:
      TOX_ENV: flake8

  deploy:
    docker:
      - image: circleci/python:latest
    working_directory: ~/zengin-py
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init
            git submodule foreach 'git pull origin master'
      - run:
          command: sudo pip install -U pip setuptools tox wheel twine
      - run:
          command: ./bin/ci/deploy

workflows:
  version: 2
  build:
    jobs:
      - build_2_7
      - build_3_4
      - build_3_5
      - build_3_6
      - build_3_7
      - build_flake8
      - deploy:
          requires:
            - build_2_7
            - build_3_4
            - build_3_5
            - build_3_6
            - build_3_7
            - build_flake8
          filters:
            branches:
              only: master

